name: Main workflow

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            ocaml-compiler: 5.2.0
          - os: macos-latest
            ocaml-compiler: 5.2.0
          - os: windows-latest
            ocaml-compiler: 5.2.0
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam install -t --deps-only .
      - run: opam exec -- dune build '@install'
      - run: opam exec -- dune runtest --force --profile=release
      - run: opam install ./sqlite3.opam
      - run: cd test-opam && opam exec -- dune runtest --force --profile=release
